version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongo-playground
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

  # docker exec -it <container-name> bash
  # mongo admin -u root -p rootpassword